### ISSUE TITLE
Strange data issue

### ISSUE THREAD

**Issue by scottcain** [andersen-lab/SARS-CoV-2_WasteWater_San-Diego#138]
I don't think this is a "issue" per se, but is weird and I was wondering if you have any insights. When I look at the Point Loma concentration data in the last few months, I frequently see pairs of data that are very close in relative value but differ considerably from nearby pairs. A good example is at the beginning of September, when you see pairs of concentrations go from around 1x10^6 to 3x10^6 to 7x10^6 then back down to 4x10^6.  I'm not saying that on average that's not what happened (obviously, I don't know) but the pairing of the data points to me suggests an issue with the sampling protocol.

**Comment by sandyarmstrong** [comment]
The highest numbers in the past month seem to be on Tues/Wed. I wonder if that is random coincidence (the trend doesn't seem to continue earlier than that), or if it suggests anything different about those days.

**Comment by joshuailevy** [comment]
It's a fair point- and something we've noted in the past as well. While I wouldn't say we have a proper answer, diet may very well be playing a role here. The wastewater viral load measurements are normalized by the concentration of PMMoV detected in the sample, which is a commonly found (and harmless) virus that infects peppers. Normally this works quite well to account for different wastewater compositions (if say, there's lots of additional water entering the system) but if we see surges or drops in PMMoV due to community dietary shifts, that could impact our normalization/measurement.  

Could well be a "taco tuesday" phenomenon at work- not quite clear. Any thoughts @watronfire?

**Comment by watronfire** [comment]
Taco Tuesday's perhaps, but I think a more likely situation is commuters during the middle of the week. Generally, a good number of people travel between San Diego and neighboring counties (Orange, LA, Imperial, Riverside) for work. With more people working a hybrid schedule nowadays, commuters peak Tuesday-Thursday ([see this article](https://laist.com/news/transportation/best-and-worst-days-to-commute-on-la-freeways)). So an idea might be that we're measuring a slightly different population midweek vs. weekend.

**Comment by scottcain** [comment]
Interesting stuff; I hadn't considered the normalization issue or the differences in the population during the week versus the weekend. Public health data is a whole 'nother beast.
